App:
  online:
    port: 80
    logPath: /data/log/
  dev:
    port: 6666
    logPath: /home/yushang/logs/golang/captcha/
Database:
  corp:
    host: 10.108.213.137
    port: 3306
    username: root
    pass: t00R
    charset: utf8
Redis:
  corp:
    host: 10.208.50.49
    port: 1616
    pass: 7b5f1e47703e914d
  bjcc:
    host: 10.142.228.31
    port: 6381
    pass: 71922dd335116341
  bjcc:
    host: 10.208.255.226
    port: 6381
    pass: 71922dd335116341
